# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Location-Area-DoCoMo-iArea
version:      2.1
version_from: lib/Location/Area/DoCoMo/iArea.pm
installdirs:  site
requires:
    Location::GeoTool:             1.97

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
